INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(1,'یاسا سروشت دەستوریەکان
',1);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(2,'یاسا شارستانیەکان',2);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(3,' یاسا سزاییەکان',3);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(4,' یاساکانی بازرگانی',4);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(5,'یاساکانی پیشەسازی',5);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(6,'یاسا کارگێڕیەکان',6);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(7,'یاسا کۆمەڵایەتیەکان',7);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(8,'یاسا داراییەکان',8);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(9,'یاسا تەندروستیەکان',9);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(10,'یاسا کشتوکاڵیەکان',10);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(11,'یاساکانی باری کەسی',11);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(12,'یاساکانی پەروەردەو خوێندنی باڵا',12);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(13,' یاساکانی سامانە سروشتیەکان',13);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(14,'یاسا هەموارکراو و جێبەجێکردنی یاسا فیدرالیەکان',14);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(15,' یاسای وەزارەت و دامەزراوەکان',15);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(16,'یاسای سەندیکاو رێکخراوەکان',16);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(17,'یاسای سەربازیەکان',17);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(18,'یاساکانی گواستنەوە',18);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(19,'یاساکانی دادو دەسەڵاتی دادواری',19);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(20,'یاساکانی رۆشنبیری',20);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(21,'یاساکانی کار',21);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(22,'بەرکارکردنی یاسا ئیتحادیەکان(فیدراڵیەکان)',22);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(23,'راگرتنی کارپێکردنی یاسا عیراقیەکان',23);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(24,'یاساکانی ژینگە',24);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(25,'کۆمەڵگەی مەدەنی',25);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(26,'یاساکانی گەشت و گوزارو شوێنەوار',26);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(27,'یاساکانی وەبەرهێنان ',27);
INSERT INTO lawtypes(law_type_id,law_type,law_type_number ) VALUES(28,'یاساکانی شارەوانی ',28);

